"""
Phase 6 — GitHub Pages Deployer
API Explorer Pipeline | GSoC 2026 | foss42/apidash
Author: Bhumika Nilesh Ujjainkar

Replaces the old Packager (zip-based approach).

Responsibilities:
  - Verify marketplace/ directory is ready for deployment
  - Generate _config.yml for GitHub Pages
  - Generate CORS headers file (needed for Flutter web fetch)
  - Verify all JSON files are valid before deployment
  - Generate deployment manifest with statistics
  - Output GitHub Pages compatible static site structure

Why no zip anymore:
  - GitHub Pages serves files directly — no zip needed
  - Flutter fetches individual JSON files on demand
  - Much more bandwidth efficient for mobile
  - No need to download everything upfront

Corner cases handled:
  - Missing marketplace directory
  - Invalid JSON files (report and skip)
  - CORS headers needed for Flutter web
  - Empty categories (skip)
  - Deployment manifest for auditing
"""

import os
import json
import time
import logging
from pathlib import Path
from fetcher import get_logger


logger = get_logger("deployer")


# ─────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────

MARKETPLACE_DIR = Path("marketplace")
DEPLOY_MANIFEST = Path("logs/deploy_manifest.json")


# ─────────────────────────────────────────────────────────────
# GitHub Pages Config Generator
# ─────────────────────────────────────────────────────────────

def generate_github_pages_config() -> str:
    """
    Generates _config.yml for GitHub Pages.
    Ensures JSON files are served with correct content type.
    """
    return """# GitHub Pages configuration for API Dash Marketplace
# Auto-generated by API Explorer Pipeline

include:
  - "*.json"

# Disable Jekyll processing — serve files as-is
plugins: []
"""


def generate_headers_file() -> str:
    """
    Generates _headers file for Netlify-style CORS headers.
    For GitHub Pages, CORS is handled differently but this
    documents the required headers for reference.

    Flutter needs:
      Access-Control-Allow-Origin: *
    to fetch JSON files from a different domain.
    """
    return """# CORS Headers for API Dash Explorer
# These headers allow the Flutter app to fetch templates
# from GitHub Pages without CORS errors

/*
  Access-Control-Allow-Origin: *
  Content-Type: application/json
  Cache-Control: public, max-age=3600
"""


# ─────────────────────────────────────────────────────────────
# Pre-deployment Verifier
# Checks all files are valid before marking ready to deploy
# ─────────────────────────────────────────────────────────────

class PreDeploymentVerifier:
    """
    Verifies the marketplace directory is ready for deployment.

    Checks:
      - index.json exists and is valid
      - All api files are valid JSON
      - All category files are valid JSON
      - No empty files
      - File count matches index entries
    """

    def verify(self, marketplace_dir: Path) -> dict:
        results = {
            "passed"        : True,
            "errors"        : [],
            "warnings"      : [],
            "file_counts"   : {},
            "total_size_kb" : 0
        }

        # Check index.json
        index_path = marketplace_dir / "index.json"
        if not index_path.exists():
            results["errors"].append("index.json missing")
            results["passed"] = False
            return results

        try:
            index = json.loads(index_path.read_text(encoding="utf-8"))
            results["file_counts"]["index_entries"] = len(index)
        except json.JSONDecodeError as e:
            results["errors"].append(f"index.json invalid: {e}")
            results["passed"] = False
            return results

        # Check api files
        apis_dir = marketplace_dir / "apis"
        api_files = list(apis_dir.glob("*.json")) if apis_dir.exists() else []
        invalid_apis = []

        for filepath in api_files:
            try:
                content = filepath.read_text(encoding="utf-8")
                if not content.strip():
                    results["warnings"].append(f"Empty file: {filepath.name}")
                    continue
                template = json.loads(content)

                # Verify required fields
                if "info" not in template or "requests" not in template:
                    invalid_apis.append(filepath.name)
                    results["errors"].append(
                        f"{filepath.name} missing required fields"
                    )

                results["total_size_kb"] += len(content) / 1024

            except json.JSONDecodeError:
                invalid_apis.append(filepath.name)
                results["errors"].append(f"{filepath.name} is invalid JSON")

        results["file_counts"]["api_files"] = len(api_files)
        results["file_counts"]["invalid_apis"] = len(invalid_apis)

        # Check category files
        cats_dir = marketplace_dir / "categories"
        cat_files = list(cats_dir.glob("*.json")) if cats_dir.exists() else []
        results["file_counts"]["category_files"] = len(cat_files)

        for filepath in cat_files:
            try:
                json.loads(filepath.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                results["warnings"].append(
                    f"Invalid category file: {filepath.name}"
                )

        # Check file count matches index
        if len(api_files) != len(index):
            results["warnings"].append(
                f"File count mismatch: {len(api_files)} files "
                f"but {len(index)} index entries"
            )

        if results["errors"]:
            results["passed"] = False

        return results


# ─────────────────────────────────────────────────────────────
# Deployment Manifest Generator
# ─────────────────────────────────────────────────────────────

def generate_deploy_manifest(marketplace_dir: Path,
                             verify_results: dict) -> dict:
    """
    Generates a deployment manifest for auditing and monitoring.
    Saved to logs/deploy_manifest.json after each run.

    Flutter app can fetch this to show "last updated" info.
    """
    index_path = marketplace_dir / "index.json"
    apis_dir   = marketplace_dir / "apis"

    # Count endpoints across all templates
    total_endpoints = 0
    category_counts = {}

    if apis_dir.exists():
        for filepath in apis_dir.glob("*.json"):
            try:
                template = json.loads(filepath.read_text(encoding="utf-8"))
                total_endpoints += len(template.get("requests", []))
            except (json.JSONDecodeError, IOError):
                pass

    # Count by category from index
    if index_path.exists():
        try:
            index = json.loads(index_path.read_text(encoding="utf-8"))
            for entry in index.values():
                for cat in entry.get("categories", []):
                    category_counts[cat] = category_counts.get(cat, 0) + 1
        except (json.JSONDecodeError, IOError):
            pass

    github_pages_url = os.environ.get("GITHUB_PAGES_URL", "").rstrip("/")

    return {
        "deployed_at"    : time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "api_count"      : verify_results["file_counts"].get("api_files", 0),
        "endpoint_count" : total_endpoints,
        "category_counts": category_counts,
        "total_size_kb"  : round(verify_results.get("total_size_kb", 0), 2),
        "verification"   : {
            "passed"  : verify_results["passed"],
            "errors"  : len(verify_results["errors"]),
            "warnings": len(verify_results["warnings"])
        },
        "github_pages_url": github_pages_url,
        "endpoints"      : {
            "index"     : "/index.json",
            "api_detail": "/apis/{api_id}.json",
            "category"  : "/categories/{category}.json",
            "search"    : "/search/index.json"
        }
    }


# ─────────────────────────────────────────────────────────────
# Main Deployer
# ─────────────────────────────────────────────────────────────

class Deployer:
    """
    Phase 6 — Prepares and verifies GitHub Pages deployment.

    GitHub Actions then commits the marketplace/ directory
    and GitHub Pages serves it automatically.

    No zip. No GitHub release assets. Just static files.
    """

    def __init__(self, marketplace_dir: str = "marketplace"):
        self.marketplace_dir = Path(marketplace_dir)

    def deploy(self) -> dict:
        logger.info("=" * 50)
        logger.info("Phase 6 — Deployer starting")
        logger.info("=" * 50)

        if not self.marketplace_dir.exists():
            logger.error("marketplace/ directory not found")
            return {"status": "failed",
                    "reason": "marketplace directory missing"}

        # Step 1: Pre-deployment verification
        logger.info("Running pre-deployment verification...")
        verifier = PreDeploymentVerifier()
        verify_results = verifier.verify(self.marketplace_dir)

        if not verify_results["passed"]:
            for error in verify_results["errors"]:
                logger.error(f"Verification error: {error}")
            return {
                "status": "failed",
                "reason": "pre-deployment verification failed",
                "errors": verify_results["errors"]
            }

        for warning in verify_results["warnings"]:
            logger.warning(f"Verification warning: {warning}")

        # Step 2: Generate .nojekyll — CRITICAL for GitHub Pages
        # Without this, GitHub Pages runs Jekyll which:
        #   - Silently drops files/dirs starting with _ (_config.yml, _headers)
        #   - May not serve .json files with correct Content-Type
        #   - Makes the entire marketplace inaccessible to Flutter
        nojekyll_path = self.marketplace_dir / ".nojekyll"
        nojekyll_path.write_text("")
        logger.debug("Generated .nojekyll")

        # Step 3: Generate GitHub Pages config
        config_path = self.marketplace_dir / "_config.yml"
        config_path.write_text(generate_github_pages_config())
        logger.debug("Generated _config.yml")

        # Step 4: Generate headers file
        headers_path = self.marketplace_dir / "_headers"
        headers_path.write_text(generate_headers_file())
        logger.debug("Generated _headers")

        # Step 5: Generate deployment manifest
        manifest = generate_deploy_manifest(
            self.marketplace_dir, verify_results
        )

        # Save manifest to logs
        DEPLOY_MANIFEST.parent.mkdir(parents=True, exist_ok=True)
        DEPLOY_MANIFEST.write_text(json.dumps(manifest, indent=2))

        # Also save manifest inside marketplace for Flutter to fetch
        marketplace_manifest = self.marketplace_dir / "manifest.json"
        marketplace_manifest.write_text(json.dumps(manifest, indent=2))

        summary = {
            "status"         : "ready",
            "api_count"      : verify_results["file_counts"].get("api_files", 0),
            "category_count" : verify_results["file_counts"].get("category_files", 0),
            "total_size_kb"  : round(verify_results.get("total_size_kb", 0), 2),
            "warnings"       : len(verify_results["warnings"]),
            "github_pages_url": manifest["github_pages_url"]
        }

        logger.info(
            f"Phase 6 complete: {summary['api_count']} APIs ready, "
            f"{summary['category_count']} categories, "
            f"{summary['total_size_kb']:.1f}KB total"
        )
        logger.info(
            f"GitHub Pages URL: {summary['github_pages_url']}"
        )

        return summary


# ─────────────────────────────────────────────────────────────
# Demo
# ─────────────────────────────────────────────────────────────

def run_demo():
    print("\n" + "="*55)
    print("  Phase 6 — Deployer Demo")
    print("="*55)

    deployer = Deployer(marketplace_dir="marketplace")
    summary  = deployer.deploy()

    print(f"\n  Status       : {summary['status']}")
    if summary["status"] == "ready":
        print(f"  APIs ready   : {summary['api_count']}")
        print(f"  Categories   : {summary['category_count']}")
        print(f"  Total size   : {summary['total_size_kb']} KB")
        print(f"  Warnings     : {summary['warnings']}")
        print(f"\n  GitHub Pages endpoints:")
        print(f"    Index    : /index.json")
        print(f"    API      : /apis/{{api_id}}.json")
        print(f"    Category : /categories/{{category}}.json")
        print(f"    Search   : /search/index.json")
        print(f"    Manifest : /manifest.json")

        # Show manifest
        if Path("marketplace/manifest.json").exists():
            manifest = json.loads(
                Path("marketplace/manifest.json").read_text(encoding="utf-8")
            )
            print(f"\n  Deployment manifest:")
            print(f"    Deployed at : {manifest['deployed_at']}")
            print(f"    APIs        : {manifest['api_count']}")
            print(f"    Endpoints   : {manifest['endpoint_count']}")
            print(f"    Categories  : {manifest['category_counts']}")
    else:
        print(f"  Reason: {summary.get('reason', 'unknown')}")

    print("\n" + "="*55)
    print("  Phase 6 complete")
    print("="*55)


if __name__ == "__main__":
    run_demo()
